### PR TITLE
Added translations to scope in order to be able to inject translated default texts

### PR DESCRIPTION
**Pull request by karlhaas**
This can be used to translate 'Choose a timezone' to different languages.

### CODE REVIEW

**Comment by ashokfernandez** [comment]
Can you please add an example to the README of how this is used?

**Comment by karlhaas** [comment]
Added a css fix because the search input field was overlapping the right border and added an example to the readme.

**Comment by ashokfernandez** [comment]
Sorry for taking so long to merge this @karlhaas, been really busy. Awesome contribution!

**Comment by ashokfernandez** [comment]
Released on bower as v1.3.0

**Pull request merged**
