### PR TITLE
Enabled translating for "Primary", "Local" .

### PR DESCRIPTION
**Pull request by akiko-pusu**
Thank you so much for this useful module!
I hope to translate "Primary" and 'Local" keyword in pulldown menu.
Could you please implement this feature?

If you need some test code to review this pull request, please let me know.

### CODE REVIEW

**Comment by ashokfernandez** [comment]
Thanks for the contribution @akiko-pusu. Can you make sure your changes pass the formatting test? Will merge as soon as they do

**Comment by akiko-pusu** [comment]
@ashokfernandez 
Thank you so much for your prompt reply! And sorry to bother you.
I’m also sorry I don’t have enough skill for angular and its testing.
It seems my pull request failed on Circle CI...

Should I drop my this pull request and submit new pull request after passing test in my environment?

**Comment by akiko-pusu** [comment]
Hi, @ashokfernandez 
I’ve removed extra space following message when I run npm test.
Should I include files under dist/\* and build/\* which generated grunt task?

**Comment by ashokfernandez** [comment]
No that's fine, I'll build it and update the bower package

**Comment by ashokfernandez** [comment]
Released as version 1.4.2

**Comment by akiko-pusu** [comment]
@ashokfernandez Thank you so much for accepting my pull request, and great plugin!

**Pull request merged**
