### PR TITLE
Fix bug in primary choices

### PR DESCRIPTION
**Pull request by tiagotex**
Before we weren't able to use timezones that included spaces, i.e,
‘America/Los Angeles’  would not work even if we wrote  ‘America/Los_Angeles’.

### CODE REVIEW

**Comment by ashokfernandez** [comment]
Thanks for the contribution. Could you change it to use the lodash `forEach` method instead of the native for loop?

https://lodash.com/docs#forEach

**Comment by tiagotex** [comment]
Yes. I will make the changes and rebase it.

**Comment by tiagotex** [comment]
@ashokfernandez Updated.

**Comment by ashokfernandez** [comment]
Thanks, released as https://github.com/mishguruorg/angular-timezone-selector/releases/tag/v1.4.0
and attribution added to the README

**Pull request merged**
